Feature and checkpoint review
andela-kndegwa/CP2 pull request #1
Opened 2016-11-12 18:44 UTC by andela-kndegwa

2016-11-14 11:08 UTC, andela-kndegwa commented
Adds comments to code on all the actions.py module.
Adds test coverage.
Uses pep8 style imports on the modules that import several functions from other modules.

Spaces out system imports with blank lines from local imports.

2016-11-14 11:08 UTC, andela-kndegwa commented
Configures the project to work with coveralls.io.

2016-11-14 11:20 UTC, malikwahab requested changes
Looks Good to me.

2016-11-14 11:20 UTC, andela-aabdulwahab commented on app/blister_api/actions.py
> +    title = data.get('title')
Get title before line 94, then you can use `title` for the `if` check to avoid calling the get statement twice.

2016-11-14 11:20 UTC, andela-aabdulwahab commented on app/blister_api/actions.py
> +    title = data.get('title')
Do the same with title here as with line 94

2016-11-14 11:51 UTC, andela-kndegwa commented on app/blister_api/actions.py
> +    title = data.get('title')
Cool.

2016-11-14 11:51 UTC, kimani-ndegwa commented on app/blister_api/actions.py
> +    title = data.get('title')
Am on it.

2016-11-14 12:21 UTC, andela-kndegwa commented
@njirap Changes as recommended by @andela-aabdulwahab made and tests rerun.

2016-11-15 09:32 UTC, andela-kndegwa commented
Hi @njirap, Kindly see the latest commit with changes as suggested by Erika if you dont mind.

2016-11-16 08:18 UTC, merged